### ISSUE TITLE
add support for configuring /etc/hosts

### ISSUE THREAD

**Issue by btrepp** [coreos/coreos-cloudinit#243]
Some support seems to exist. It would be great if there was the option to override more. I haven't coded go, but I imagine you would allow a format like

```
manage_etc_hosts:
      - "127.0.0.1 localhost"
      - "127.0.0.1 someotherdomain"
```

**Comment by brianclements** [comment]
Write now, this done via the 'write_files' directive. If you drop a custom `/etc/hosts` in, make sure you remove the "manage_etc_hosts" line in your yml file though or else it will overwrite your custom file with a blank "127.0.0.1 localhost" one that it does by default.

Supporting this component of cloud-config seems long overdue to me, but because the fix is quite easy, I can see why it's been overlooked. But that overwriting part of it was a bit annoying to figure out for sure.

**Comment by IbnSaeed** [comment]
@brianclements Can you please list the steps in order to make the required change you mentioned above.

How would i write the write_files ?

**Comment by johnt337** [comment]
```
write_files:
   - path: /etc/hosts
     content: |
        127.0.0.1     localhost
        x.x.x.y          somehost
        ....
```
