### ISSUE TITLE
suggestion: update examples to prevent Ruby YAML parsing errors

### ISSUE THREAD

**Issue by JeanMertz** [coreos/coreos-cloudinit#316]
Today, I ran into an unexpected problem that cost me a couple of hours to figure out.

First of all, we use Vagrant during testing, and since we are lazy, we've added the following snippet to auto-update the `etcd` discovery key on boot:

```ruby
if ARGV[0] == 'up'
  require 'open-uri'
  require 'yaml'

  token = open('https://discovery.etcd.io/new').read

  data = YAML.load(File.read('user-data.yml'))
  data['coreos']['etcd']['discovery'] = token

  File.write('user-data.yml', "#cloud-config\n\n#{YAML.dump(data)}")
end
```

This works, but it also caused some errors that we only later found out where caused by this code block.

1. digits starting with a leading 0 get treated as an octal, and upon re-writing the user-data file, is returned as a different digit. This causes the `write_files` example to fail, because `0644` gets rewritten to `420`, which in turn caused `resolv.conf` to become unreadable, and thus everything requiring a DNS lookup to fail.

2. `off` gets rewritten as `false`, causing problems with the `reboot-strategy` key, which we set to off during test runs.

Both are easily solved (add quotes around the values), but where hard to debug, and perhaps this could be mentioned somewhere (either watching out how Yaml handles digits starting with 0, and `off`, or simply quoting all of those cases in the examples.

**Comment by crawford** [comment]
Welcome to the pain train. Loose typing is so great.

We can explicitly specify everything as their proper type. I think I would rather express file permissions as a decimal number (yes, that is _also_ supported): `permissions: 644`.

**Comment by marineam** [comment]
Just to be clear, the reason why we treat the permissions field as octal regardless of whether it is written `0644` or `644` is for consistency with tools like chmod. A lot of people were bitten when we let yaml interpret the value as decimal. Internally the type of that field is interpreted as a string.

I don't have a great answer, the root of the issue is yaml doesn't require strings to be quoted so yaml is rarely written with quotes. If you need the ability to run the config through a yaml parser that infers the types from the config instead of a strict definition like cloudinit does you need to quote strings.

**Comment by JeanMertz** [comment]
@crawford @marineam thank you for your answers. I agree there is no easy solution to this, but perhaps having the docs have "special case" strings actually be in quotes, would make it less likely for people to run into this.

So have it show `'0644'` and `'off` where required.

If you don't feel like this is worth a change, then I don't mind, I've solved it now and will probably not be bitten by this again, but perhaps this issue (and/or a possible fix) will help others in the future :+1:
