### ISSUE TITLE
Add -from-s3 option to read data from S3 URL

### ISSUE THREAD

**Issue by vaijab** [coreos/coreos-cloudinit#331]
AWS launch configuration being immutable when using auto scaling groups does not help at all. S3 https URLs do not have flexible ACLs either. `coreos-cloudinit` supports reading configuration from URL already, but it has to be public, which is not ideal.

So by adding cloudinit s3:// support solves the issue described above. Do people agree? If so, I could potentially write support for that.

**Comment by vaijab** [comment]
Any comments on this? Thanks.

**Comment by crawford** [comment]
Is the intent of this proposal to provide a mutable cloud-config to your cluster?

**Comment by vaijab** [comment]
> Is the intent of this proposal to provide a mutable cloud-config to your cluster?

To certain degree, yes. This proposal is rather for making changes to `user-data` possible when CoreOS runs in auto scaling group on AWS without a termination of an instance. How people implement this approach it is up to them I guess.

**Comment by crawford** [comment]
To be completely upfront, I do not like the idea of using coreos-cloudinit for configuration management. It was never designed to do this and it's really bad at it. It sounds like you want to work around the immutable nature of the auto scaling group. May I ask why? Is it for ease of development or do need this flexibility in production? The other consideration to be made is that in order to run with this flag, your user data will need to be a script. Given that, why not implement all of the logic to fetch the "second stage" user data in the script? Is that a straightforward call to curl or does that require a utility?

**Comment by vaijab** [comment]
@crawford thanks for reply. The way I have it done now is I pull a tool which supports fetching files from S3 and then run cloudinit with `--from-file` argument. That works pretty well.

It is not a big deal and having immutable configuration definitely makes sense, but in certain situations, having to replace an entire cluster just to remove an ssh key from `authorized_keys` seems a little wasteful.

I am closing this issue. Thanks.

**Comment by crawford** [comment]
> having to replace an entire cluster just to remove an ssh key
There is a lot of room for improvement here. My next area of focus is going to be on provisioning and configuration management. We don't have a good answer for this right now but as you've noticed, we need one.

**Comment by vaijab** [comment]
@crawford great and thanks for that. Let me know if you need any help testing, etc.
