### ISSUE TITLE
coreos-ssh-import-github causes network failure on DigitalOcean

### ISSUE THREAD

**Issue by bobbytables** [coreos/coreos-cloudinit#332]
When you use the `coreos-ssh-import-github` to create SSH key's on DigitalOcean, SSH'ing into a droplet times out. Reproducible consistently.

**Comment by mischief** [comment]
@bobbytables can you look at the machines console and see if it has a publicly accessible ip?

**Comment by mischief** [comment]
bug spotted. coreos-cloudinit tries to pull the keys from github while setting up users before configuring the interfaces, and when the requests to github fail, cloudinit aborts, leaving you with the network unconfigured. 

see https://github.com/coreos/coreos-cloudinit/blob/master/initialize/config.go#L45

cc @crawford

**Comment by crawford** [comment]
Same root cause as https://github.com/coreos/coreos-cloudinit/issues/215. This class of bugs is due to a deep design flaw. In some scenarios, coreos-cloudinit is responsible for configuring the network; in others, it depends on the network.

My suggestion would be to include your key directly in the config via ssh-authorized-keys. The coreos-ssh-import-github feature really should have never been introduced, but it has been kept for backward compatibility. :(

**Comment by bobbytables** [comment]
Cool thanks :)

**Comment by JeanMertz** [comment]
I ran into the same issue where on bare-meta, the CoreOS `user` directive ran before our `*.network` units where processed, resulting in a timeout when using `coreos-ssh-import-github`.

We'll be solving it by using `ssh-authorized-keys`. Too bad network units can't be loaded before the users configurations are set.
